; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv ; default table caps app at 1MB; WiFi+MQTT needs more (see partitions.csv)

monitor_speed = 921600
monitor_port = COM3
upload_port = COM3

build_flags = 
    -D CONFIG_LOG_DEFAULT_LEVEL=3 ; ensures info level logs are printed (LEVELS: 0=NONE, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG, 5=VERBOSE)
monitor_filters = esp32_exception_decoder ; if code ever crashes, auto decode the stack trace to human readable form
